---

name: Build and Push

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Docker Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image.
        run: docker build -t azdo-container-image .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'azdo-container-image'
          format: 'table'
          # uncomment to fail on found issues with defined severity
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL' #,HIGH

      - name: Run the built image.
        run: docker run --name test-container --entrypoint "/bin/sleep" -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro azdo-container-image 60

      - name: Verify tools are accessible in the built image.
        run: |
          set -e
          docker exec --tty test-container env TERM=xterm  wget --version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=sha
            type=semver,pattern={{version}}
            type=ref,event=branch
            stable
          flavor: |
            latest=true

      - name: Push image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          context: .
          push: true

